In [3]:
import torch

In [4]:
vision_outputs = [torch.tensor([1,1,1]), torch.tensor([1,1,1])]

In [6]:
image_embeds = vision_outputs[1]

In [7]:
image_embeds

tensor([1, 1, 1])

In [8]:
image_embeds.dim()

1

In [27]:
ids = torch.tensor([-1,1,1])

In [15]:
mask = ids.ne(1)

In [16]:
mask

tensor([False, False, False])

In [20]:
zero_tensor = torch.tensor(0).to(ids)# 这个和

In [21]:
zero_tensor

tensor(0)

In [30]:
ids

tensor([0, 1, 1])

In [29]:
ids = ids.maximum(zero_tensor)

In [41]:
ids

tensor([0, 1, 1])

In [46]:
embed = torch.relu(ids)

In [49]:
embed

tensor([0, 1, 1, 0, 1, 1])

In [33]:
embed = torch.tanh(embed)

In [48]:
embed = torch.cat([embed, ids], dim=-1)

In [52]:
inputs = torch.tensor([[ 1.,  2.,  3.,  4.],

        [ 2.,  4.,  6.,  8.],

        [ 3.,  6.,  9., 12.]])

In [61]:
outputs1 = inputs.norm(p=2, dim=1, keepdim=False)

In [66]:
outputs1

tensor([[ 5.4772],
        [10.9545],
        [16.4317]])

In [55]:
outputs1 = inputs.norm(p=2, dim=1, keepdim=True)

In [65]:
outputs1 = inputs.norm(p=2, dim=-1, keepdim=True)

In [63]:
outputs1 = inputs.norm(p=2, dim=0, keepdim=True)